/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as OnboardingRouteImport } from './routes/onboarding'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AppRouteRouteImport } from './routes/_app/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AppWeeklyWrappedRouteImport } from './routes/_app/weekly-wrapped'
import { Route as AppTraniningCalendarRouteImport } from './routes/_app/tranining-calendar'
import { Route as AppPlannerRouteImport } from './routes/_app/planner'
import { Route as AppHistoryRouteImport } from './routes/_app/history'
import { Route as AppGoalsRouteImport } from './routes/_app/goals'
import { Route as AppDashboardRouteImport } from './routes/_app/dashboard'
import { Route as AppAvailabilityRouteImport } from './routes/_app/availability'
import { Route as AppAnalyticsRouteImport } from './routes/_app/analytics'
import { Route as AppActivityActivityIdRouteImport } from './routes/_app/activity.$activityId'

const OnboardingRoute = OnboardingRouteImport.update({
  id: '/onboarding',
  path: '/onboarding',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRouteRoute = AppRouteRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AppWeeklyWrappedRoute = AppWeeklyWrappedRouteImport.update({
  id: '/weekly-wrapped',
  path: '/weekly-wrapped',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppTraniningCalendarRoute = AppTraniningCalendarRouteImport.update({
  id: '/tranining-calendar',
  path: '/tranining-calendar',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppPlannerRoute = AppPlannerRouteImport.update({
  id: '/planner',
  path: '/planner',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppHistoryRoute = AppHistoryRouteImport.update({
  id: '/history',
  path: '/history',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppGoalsRoute = AppGoalsRouteImport.update({
  id: '/goals',
  path: '/goals',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppDashboardRoute = AppDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppAvailabilityRoute = AppAvailabilityRouteImport.update({
  id: '/availability',
  path: '/availability',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppAnalyticsRoute = AppAnalyticsRouteImport.update({
  id: '/analytics',
  path: '/analytics',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppActivityActivityIdRoute = AppActivityActivityIdRouteImport.update({
  id: '/activity/$activityId',
  path: '/activity/$activityId',
  getParentRoute: () => AppRouteRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/onboarding': typeof OnboardingRoute
  '/analytics': typeof AppAnalyticsRoute
  '/availability': typeof AppAvailabilityRoute
  '/dashboard': typeof AppDashboardRoute
  '/goals': typeof AppGoalsRoute
  '/history': typeof AppHistoryRoute
  '/planner': typeof AppPlannerRoute
  '/tranining-calendar': typeof AppTraniningCalendarRoute
  '/weekly-wrapped': typeof AppWeeklyWrappedRoute
  '/activity/$activityId': typeof AppActivityActivityIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/onboarding': typeof OnboardingRoute
  '/analytics': typeof AppAnalyticsRoute
  '/availability': typeof AppAvailabilityRoute
  '/dashboard': typeof AppDashboardRoute
  '/goals': typeof AppGoalsRoute
  '/history': typeof AppHistoryRoute
  '/planner': typeof AppPlannerRoute
  '/tranining-calendar': typeof AppTraniningCalendarRoute
  '/weekly-wrapped': typeof AppWeeklyWrappedRoute
  '/activity/$activityId': typeof AppActivityActivityIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_app': typeof AppRouteRouteWithChildren
  '/login': typeof LoginRoute
  '/onboarding': typeof OnboardingRoute
  '/_app/analytics': typeof AppAnalyticsRoute
  '/_app/availability': typeof AppAvailabilityRoute
  '/_app/dashboard': typeof AppDashboardRoute
  '/_app/goals': typeof AppGoalsRoute
  '/_app/history': typeof AppHistoryRoute
  '/_app/planner': typeof AppPlannerRoute
  '/_app/tranining-calendar': typeof AppTraniningCalendarRoute
  '/_app/weekly-wrapped': typeof AppWeeklyWrappedRoute
  '/_app/activity/$activityId': typeof AppActivityActivityIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/onboarding'
    | '/analytics'
    | '/availability'
    | '/dashboard'
    | '/goals'
    | '/history'
    | '/planner'
    | '/tranining-calendar'
    | '/weekly-wrapped'
    | '/activity/$activityId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/onboarding'
    | '/analytics'
    | '/availability'
    | '/dashboard'
    | '/goals'
    | '/history'
    | '/planner'
    | '/tranining-calendar'
    | '/weekly-wrapped'
    | '/activity/$activityId'
  id:
    | '__root__'
    | '/'
    | '/_app'
    | '/login'
    | '/onboarding'
    | '/_app/analytics'
    | '/_app/availability'
    | '/_app/dashboard'
    | '/_app/goals'
    | '/_app/history'
    | '/_app/planner'
    | '/_app/tranining-calendar'
    | '/_app/weekly-wrapped'
    | '/_app/activity/$activityId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppRouteRoute: typeof AppRouteRouteWithChildren
  LoginRoute: typeof LoginRoute
  OnboardingRoute: typeof OnboardingRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/onboarding': {
      id: '/onboarding'
      path: '/onboarding'
      fullPath: '/onboarding'
      preLoaderRoute: typeof OnboardingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/weekly-wrapped': {
      id: '/_app/weekly-wrapped'
      path: '/weekly-wrapped'
      fullPath: '/weekly-wrapped'
      preLoaderRoute: typeof AppWeeklyWrappedRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/_app/tranining-calendar': {
      id: '/_app/tranining-calendar'
      path: '/tranining-calendar'
      fullPath: '/tranining-calendar'
      preLoaderRoute: typeof AppTraniningCalendarRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/_app/planner': {
      id: '/_app/planner'
      path: '/planner'
      fullPath: '/planner'
      preLoaderRoute: typeof AppPlannerRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/_app/history': {
      id: '/_app/history'
      path: '/history'
      fullPath: '/history'
      preLoaderRoute: typeof AppHistoryRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/_app/goals': {
      id: '/_app/goals'
      path: '/goals'
      fullPath: '/goals'
      preLoaderRoute: typeof AppGoalsRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/_app/dashboard': {
      id: '/_app/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AppDashboardRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/_app/availability': {
      id: '/_app/availability'
      path: '/availability'
      fullPath: '/availability'
      preLoaderRoute: typeof AppAvailabilityRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/_app/analytics': {
      id: '/_app/analytics'
      path: '/analytics'
      fullPath: '/analytics'
      preLoaderRoute: typeof AppAnalyticsRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/_app/activity/$activityId': {
      id: '/_app/activity/$activityId'
      path: '/activity/$activityId'
      fullPath: '/activity/$activityId'
      preLoaderRoute: typeof AppActivityActivityIdRouteImport
      parentRoute: typeof AppRouteRoute
    }
  }
}

interface AppRouteRouteChildren {
  AppAnalyticsRoute: typeof AppAnalyticsRoute
  AppAvailabilityRoute: typeof AppAvailabilityRoute
  AppDashboardRoute: typeof AppDashboardRoute
  AppGoalsRoute: typeof AppGoalsRoute
  AppHistoryRoute: typeof AppHistoryRoute
  AppPlannerRoute: typeof AppPlannerRoute
  AppTraniningCalendarRoute: typeof AppTraniningCalendarRoute
  AppWeeklyWrappedRoute: typeof AppWeeklyWrappedRoute
  AppActivityActivityIdRoute: typeof AppActivityActivityIdRoute
}

const AppRouteRouteChildren: AppRouteRouteChildren = {
  AppAnalyticsRoute: AppAnalyticsRoute,
  AppAvailabilityRoute: AppAvailabilityRoute,
  AppDashboardRoute: AppDashboardRoute,
  AppGoalsRoute: AppGoalsRoute,
  AppHistoryRoute: AppHistoryRoute,
  AppPlannerRoute: AppPlannerRoute,
  AppTraniningCalendarRoute: AppTraniningCalendarRoute,
  AppWeeklyWrappedRoute: AppWeeklyWrappedRoute,
  AppActivityActivityIdRoute: AppActivityActivityIdRoute,
}

const AppRouteRouteWithChildren = AppRouteRoute._addFileChildren(
  AppRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppRouteRoute: AppRouteRouteWithChildren,
  LoginRoute: LoginRoute,
  OnboardingRoute: OnboardingRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
